### PR TITLE
added concept string.rf - couldn't test due to bug

### PR DESCRIPTION
**Pull request by HilbertCurve**
small changes

### CODE REVIEW

**Comment by HilbertCurve** [comment]
bugfixes include:
function mangling adding spaces when parameter was of pointer type
varargs parameter name not being recognized

**Comment by PixelRifts** [comment]
These bugs just always keep coming dang it

**Comment by PixelRifts** [comment]
Is this pr ready for merging on your side?

**Comment by HilbertCurve** [comment]
yeah i think so; when I `git merge` or `git pull` it says everything's up to date and the github front page doesn't say there are any conflicts

**Comment by PixelRifts** [comment]
Ye, Since you opened this pr and then added commits, I had no way of knowing whether you were planning to add any more. Gonna merge now

**Pull request merged**
